In [6]:
import numpy as np
import random
a = []
for _ in range(20):
  a.append(random.randint(1,100))
arr = np.array(a)
np.sort(arr)
print(arr)
print(f"Mean : {arr.mean()} \n Median : {np.median(arr)} \n Stdev : {arr.std()}")


[12 48 40 50 24 26 43 57 53 12 68 12 34 23 55 89 58 50 15 44]
Mean : 40.65 
 Median : 43.5 
 Stdev : 20.281210516140305


In [7]:
even = arr[arr % 2 == 0]
even

array([12, 48, 40, 50, 24, 26, 12, 68, 12, 34, 58, 50, 44])

In [18]:
arr = np.random.randint(1, 100, size=(5, 4))
print(arr)
print('\n')
sliced_arr = arr[:3, :]
print(sliced_arr)

[[ 4 58 75 47]
 [ 5 67 63 64]
 [59  8 72 90]
 [94 82 75 90]
 [90 63 51 69]]


[[ 4 58 75 47]
 [ 5 67 63 64]
 [59  8 72 90]]
